//
//  UIColor+HSAdditions.h
//
//  Generated by Zeplin on 4/16/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (HSAdditions)

+ (UIColor *)hs_mainColor;
+ (UIColor *)hs_contentBlackColor;

@end
