//
//  UIColor+HSAdditions.m
//
//  Generated by Zeplin on 4/16/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+HSAdditions.h"

@implementation UIColor (HSAdditions)

+ (UIColor *)hs_mainColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:77.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)hs_contentBlackColor {
	return [UIColor colorWithWhite:33.0f / 255.0f alpha:1.0f];
}

@end
